apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boj-archive-ingress
  namespace: boj-archive
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: "boj.xn--hy1by51c.kr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boj-archive-service
                port:
                  number: 8000
    - host: "xn--3h3b87u.xn--hy1by51c.kr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boj-archive-service
                port:
                  number: 8000
  tls:
    - hosts:
        - "boj.xn--hy1by51c.kr"
        - "xn--3h3b87u.xn--hy1by51c.kr"
      secretName: boj-archive-tls
