apiVersion: v1
kind: Service
metadata:
  name: boj-archive-service
  namespace: boj-archive
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8899
---
apiVersion: v1
kind: Endpoints
metadata:
  name: boj-archive-service
  namespace: boj-archive
subsets:
  - addresses:
      - ip: 192.168.0.100
    ports:
      - port: 8899
